<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE shakemap-data [
<!ELEMENT shakemap-data (earthquake,stationlist)>
<!ELEMENT stationlist (station+)>
<!ATTLIST stationlist
  created	CDATA	#REQUIRED
>

<!ELEMENT station (comp+)>
<!ATTLIST station
  code		CDATA 			#REQUIRED
  name		CDATA 			#REQUIRED
  insttype	CDATA 			#REQUIRED
  lat		CDATA 			#REQUIRED
  lon		CDATA 			#REQUIRED
  source	(SCSN|CGS|NSMP) 	'SCSN'
  netid		CDATA			#REQUIRED
  commtype	(DIG|ANA) 		'DIG'
  dist          CDATA                   '10.0'
  loc		CDATA			''
>

<!ELEMENT comp (acc,vel,psa*)>
<!ATTLIST comp
  name          CDATA  #REQUIRED
  originalname  CDATA  #IMPLIED
>

<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc
  value  CDATA         #REQUIRED
  flag   CDATA        ''
>
<!ATTLIST vel
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa03
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa10
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa30
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ELEMENT  earthquake EMPTY>
<!ATTLIST earthquake
  id 		ID	#REQUIRED
  lat		CDATA	#REQUIRED
  lon		CDATA	#REQUIRED
  mag		CDATA	#REQUIRED
  year          CDATA   #REQUIRED
  month         CDATA   #REQUIRED
  day           CDATA   #REQUIRED
  hour          CDATA   #REQUIRED
  minute        CDATA   #REQUIRED
  second        CDATA   #REQUIRED
  timezone      CDATA   #REQUIRED
  depth		CDATA	#REQUIRED
  type		CDATA	#REQUIRED
  locstring	CDATA	#REQUIRED
  pga		CDATA   #REQUIRED
  pgv		CDATA   #REQUIRED
  sp03		CDATA   #REQUIRED
  sp10		CDATA   #REQUIRED
  sp30		CDATA   #REQUIRED
  created	CDATA	#REQUIRED
>
]>
<shakemap-data code_version="3.5" map_version="454">
<earthquake id="20251009065806_34_-2310_140550_20251009065806" lat="-2.31" lon="140.55" mag="3.4" year="2025" month="10" day="09" hour="06" minute="58" second="06" timezone="WIB" depth="9.0" network="" locstring="32 km BaratLaut KOTA-JAYAPURA-PAPUA" created="1759968799" />
<stationlist created="1759968799">
<station code="JBPI" name="JBPI" insttype="Titan Accelerometer" lat="-2.57" lon="140.68" dist="32.317304" source="BMKG" netid="IA" commtype="" loc="" intensity="1.7">
<comp name="--.HNE">
<acc value="0.1497" flag="0" />
<vel value="0.0298" flag="0" />
<psa03 value="0.1297" flag="0" />
<psa10 value="0.0079" flag="0" />
<psa30 value="0.0006" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.1462" flag="0" />
<vel value="0.0348" flag="0" />
<psa03 value="0.2289" flag="0" />
<psa10 value="0.0090" flag="0" />
<psa30 value="0.0008" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.1155" flag="0" />
<vel value="0.0249" flag="0" />
<psa03 value="0.0877" flag="0" />
<psa10 value="0.0035" flag="0" />
<psa30 value="0.0004" flag="0" />
</comp>
</station>
<station code="JGPI" name="JGPI" insttype="Titan Accelerometer" lat="-2.51445" lon="140.704" dist="28.452421" source="BMKG" netid="IA" commtype="" loc="" intensity="2.8">
<comp name="--.HNE">
<acc value="0.5101" flag="0" />
<vel value="0.1390" flag="0" />
<psa03 value="0.6375" flag="0" />
<psa10 value="0.0211" flag="0" />
<psa30 value="0.0024" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.5135" flag="0" />
<vel value="0.1233" flag="0" />
<psa03 value="0.4309" flag="0" />
<psa10 value="0.0202" flag="0" />
<psa30 value="0.0019" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.4930" flag="0" />
<vel value="0.0732" flag="0" />
<psa03 value="0.1234" flag="0" />
<psa10 value="0.0059" flag="0" />
<psa30 value="0.0006" flag="0" />
</comp>
</station>

</stationlist>
</shakemap-data>
